<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Resources\Icons\PayBeat.ico</ApplicationIcon>
    <AssemblyName>PayBeat</AssemblyName>
    <RootNamespace>PayBeat.App</RootNamespace>
    <PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Resources\Icons\PayBeat.ico" />
    <Resource Include="Resources\Screenshots\*.png" />
    <EmbeddedResource Include="Resources\holidays.json" />
  </ItemGroup>
    
</Project>
